security:
    encoders:
        App\Document\User:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            # entity:
                # class: App\Document\User
            # id: App\Security\UserProvider
            mongodb:
                class: App\Document\User
                # property: option

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # login:
        #     pattern: ^/api/v1/auth
        #     stateless: true
        #     anonymous: true
        #     form_login:
        #         username_parameter: email
        #         password_parameter: password
        #         check_path: api_login_check
        #         success_handler: lexik_jwt_authentication.handler.authentication_success
        #         failure_handler: lexik_jwt_authentication.handler.authentication_failure

        login:
            pattern: ^/api/v1/auth/login
            stateless: true
            anonymous: true
            guard:
                authenticators:
                    - App\Security\UserAuthenticator
        
        signup:
            pattern: ^/api/v1/auth/signup
            stateless: true
            anonymous: true
                
                

            # json_login:
            #     username_path: email
            #     password_path: password
            #     check_path: api_login_check
            #     success_handler: lexik_jwt_authentication.handler.authentication_success
            #     failure_handler: lexik_jwt_authentication.handler.authentication_failure
        
        
        # questions_gateway:
        #     pattern: ^/api/v1/questions
        #     stateless: true
        #     anonymous: true 
        
        api:
            pattern: ^/api/v1/
            stateless: true
            guard:
                authenticators:
                    # - App\Security\UserAuthenticator
                    - lexik_jwt_authentication.jwt_token_authenticator


        main:
            anonymous: true

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/api/v1/questions, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/api/v1/auth, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/v1/, roles: IS_AUTHENTICATED_FULLY}
